Navbar
E-Dragon-Project/E-Dragon-MVP pull request #11
Opened 2021-02-21 10:59 UTC by Nov66

Added:
 1. public新建assets文件夹放了 logo 以及 icon
 2. styles 下的 globas. css import 了导航栏所需字体

Achieved:

- 导航栏静态部分
-  页面可切换
- 导航栏可显示在每个页面

2021-02-21 11:37 UTC, KieraDOG commented
@hachilam92 这个pr eslint 没工作 你看一下 可能是他本地没有初始化 yarn

2021-02-21 21:59 UTC, JavaScriptN0ob commented
@Nov66 N，具体放静态资源的位置有变化，请查看https://trello.com/c/AzEekFvN/41-project-structure项目结构

2021-02-21 22:01 UTC, JavaScriptN0ob commented
还想提一个缩进问题，全局缩进要保持统一。
目前应该是 tab = 2 * spaces；

2021-02-21 23:13 UTC, KieraDOG commented
> @Nov66 N，具体放静态资源的位置有变化，请查看https://trello.com/c/AzEekFvN/41-project-structure 项目结构

静态资源我周末看了一下，还是用 pulic 目录
不过我在纠结要不要
```
/public/images
/public/fonts
/public/...
```

2021-02-21 23:14 UTC, KieraDOG commented
> 还想提一个缩进问题，全局缩进要保持统一。
> 目前应该是 tab = 2 * spaces；

他这个本地应该没有装最新的 yarn 包 `yarn --forzen-lockfile` 所以 eslint 没工作

2021-02-21 23:14 UTC, KieraDOG requested changes
lint

2021-02-21 23:56 UTC, JavaScriptN0ob commented
> > @Nov66 N，具体放静态资源的位置有变化，请查看https://trello.com/c/AzEekFvN/41-project-structure 项目结构
> 
> 静态资源我周末看了一下，还是用 pulic 目录
> 不过我在纠结要不要
> 
> ```
> /public/images
> /public/fonts
> /public/...
> ```

我觉得要分开，足够的single responsibility，提现代码pattern的RMR

2021-02-21 23:57 UTC, KieraDOG commented
> > > @Nov66 N，具体放静态资源的位置有变化，请查看https://trello.com/c/AzEekFvN/41-project-structure 项目结构
> > 
> > 
> > 静态资源我周末看了一下，还是用 pulic 目录
> > 不过我在纠结要不要
> > ```
> > /public/images
> > /public/fonts
> > /public/...
> > ```
> 
> 我觉得要分开，足够的single responsibility，提现代码pattern的RMR

这里主要是因为迎合 nextjs 自身的设计 https://nextjs.org/docs/api-reference/next/image

2021-02-22 04:27 UTC, Nov66 commented
@JavaScriptN0ob  维尼 我改好了 所有格式问题也lint了 public的文件夹也 re-structure 了 你看看还有什么问题要改进 
  a. public 下我增加了 images 和 font 
b. 然后 images 的 folder 下 分了 logo 和 icons (icons 为了以后还有需要引入的icon 这样层次更清晰？)

2021-02-22 04:30 UTC, Nov66 commented
<img width="745" alt="Screen Shot 2021-02-22 at 15 29 10" src="https://user-images.githubusercontent.com/75833339/108662558-b7ec8100-7522-11eb-9af1-43af565763d6.png">

@KieraDOG 龙哥这是截图

2021-02-22 04:32 UTC, Nov66 commented
> <img alt="Screen Shot 2021-02-22 at 15 29 10" width="745" src="https://user-images.githubusercontent.com/75833339/108662558-b7ec8100-7522-11eb-9af1-43af565763d6.png">
> 
> @KieraDOG 龙哥这是截图

2021-02-22 04:35 UTC, JavaScriptN0ob commented
目前看着截图跟UI设计一致，我现在看看代码

2021-02-22 04:38 UTC, JavaScriptN0ob commented on src/app/Header/Header.jsx
> +    <MenuLeft />
这四个components中间不需要空行

2021-02-22 04:47 UTC, JavaScriptN0ob reviewed
LGTM，需要龙哥确认下SC里面包裹了li 包括pseudo伪类的 css选择器是不是建议这样用。
@KieraDOG

2021-02-22 04:48 UTC, JavaScriptN0ob commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +const SearchBar = styled.div`
关于SC内的css选择器 --- 锚点

2021-02-22 04:55 UTC, KieraDOG commented
> LGTM，需要龙哥确认下SC里面包裹了li 包括pseudo伪类的 css选择器是不是建议这样用。
> @KieraDOG

不建议，不要用

2021-02-22 04:57 UTC, KieraDOG submitted a review, later dismissed
选择器改一下，其余的 LGTM 👍  CSS 做得不错

2021-02-22 07:48 UTC, JavaScriptN0ob submitted a review, later dismissed
把那个typo忘记删的改好就ok了，我这边先approve啦

2021-02-22 07:48 UTC, JavaScriptN0ob commented on src/app/Header/components/MenuLeft/MenuLeft.jsx
> +  a {
这里忘记删了 - -，删掉就应该ok啦， LGTM

2021-02-22 07:52 UTC, SimonYu-Web submitted a review, later dismissed
LGTM👍  要是没有其他需要改的就可以merge了

2021-02-22 07:53 UTC, Nov66 commented on src/app/Header/components/MenuLeft/MenuLeft.jsx
> +  a {
好的 改好了

2021-02-22 09:21 UTC, jessieease submitted a review, later dismissed
looks good to me

2021-02-22 09:46 UTC, KieraDOG submitted a review, later dismissed

2021-02-22 09:46 UTC, KieraDOG commented on src/app/Header/components/Logo/Logo.jsx
> +  <>
其实这里可以做 SemiCircle 里面 包括一个 Link

SemiCircle 做 position 人啊后 flex 水平垂直居中 现在这个逻辑 图片不在 div 中间

2021-02-22 09:46 UTC, KieraDOG commented on src/app/Header/components/Logo/Logo.jsx
> +  <>
不过改不改都行 这里以后肯定会换设计

2021-02-22 09:46 UTC, KieraDOG commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +      }
缩紧格式

2021-02-22 09:48 UTC, Nov66 commented on src/app/Header/components/Logo/Logo.jsx
> +  <>
好的

2021-02-22 09:53 UTC, Nov66 commented on src/app/Header/components/MenuRight/MenuRight.jsx
> +      }
已改

2021-02-22 10:20 UTC, SimonYu-Web approved these changes
👍

2021-02-22 10:56 UTC, hachilam92 approved these changes
LGTM

2021-02-22 11:22 UTC, merged