Js noob/add pages -> master: Initial pages had been added & manualy tested
E-Dragon-Project/E-Dragon-MVP pull request #4
Opened 2021-02-17 22:43 UTC by JavaScriptN0ob

***
- ``localhost:3000/``
now will directly route to our landing page with header & footer.
---
- ``localhost:3000/map``:
now will jump to map page.
---
- ``localhost:3000/product?productId=123``:
now will jump to product page
---
- ``localhost:3000/user/profile``:
now will jump to user profile page
***

2021-02-17 22:46 UTC, JavaScriptN0ob commented
现在有一个我还没搞明白的的bug，在于我添加SC(styled-components)之后，live server无法马上反映到页面上。
只有当我control + C，并且在此yarn dev之后才会出现在页面上，并且一旦加载其他页面后，css仍无法生效。
应该与Next.js pre-render机制有关，请 @KieraDOG @SimonYu-Web 审核一下。

2021-02-18 04:22 UTC, JavaScriptN0ob commented
- [x]: 已经_*引入`_document.js`*_解决了，SC无法及时加载的问题。 同时改变了项目文件解构，提升可读性与维护性。
- [x]: 添加了Trello里需要添加的卡片，具体看卡片内容，已经进行了__*基础和搭配SC*__的*手动测试*。

2021-02-18 08:39 UTC, KieraDOG requested changes

2021-02-18 08:39 UTC, KieraDOG commented on src/pages/index.jsx
> +
import 不要空行

2021-02-18 08:39 UTC, KieraDOG commented on src/pages/index.jsx
> +
这个文件应该是不包括任何东西

```

import LandingPage...

export default LandingPage
```

2021-02-18 08:39 UTC, KieraDOG commented on src/pages/products.jsx
> +const Product = () => (
参考 index 的 comment

2021-02-18 08:39 UTC, KieraDOG commented on src/pages/map.jsx
> +const Map = () => (
参考 index 的 comment

2021-02-18 08:39 UTC, KieraDOG commented on src/pages/user/profile.jsx
> +const Profile = () => (
同上

2021-02-18 08:51 UTC, JavaScriptN0ob commented
@KieraDOG 已完成import以及pages/内变成纯路由仅用于import & export，同时修改文件后缀回js

2021-02-18 10:29 UTC, KieraDOG approved these changes

2021-02-18 12:06 UTC, SimonYu-Web approved these changes
👍
👍
👍

2021-02-18 12:52 UTC, merged